language: cpp
compiler: gcc
os: linux

services:
  - docker

matrix:
  include:
  - env: DIST=ubuntu:xenial MODE=safe
  - env: DIST=ubuntu:xenial MODE=unsafe
  - env: DIST=ubuntu:bionic MODE=unsafe

before_install:
  - NAME=qs-${MODE}-${DIST}
  - docker build -f Dockerfile.${NAME} -t ${NAME} .

install:
  - SH="docker run -t -e LC_ALL=en_US.UTF-8 -e LANG=en_US.UTF-8 ${NAME} bash -c"

script:
  - $SH "tools/run-autotests.sh"
  - $SH "tools/run-e2e-tests.sh $MODE"
