#
# Docker environment for QSSLCAUDIT testing
# Uses binary packages of unsafe OpenSSL
#
# Prepare image: docker build -t qs-unsafe-ubuntu:bionic -f Dockerfile.qs-unsafe-ubuntu:bionic .
# Run instance:  docker run --rm -it qs-unsafe-ubuntu:bionic
#
FROM ubuntu:bionic

RUN apt-get update && apt-get install -y wget git time

ADD . /qsslcaudit
WORKDIR /qsslcaudit

RUN tools/install-deps.sh unsafe ubuntu:bionic
RUN tools/install.sh

RUN apt-get install -y curl vim libxml-xpath-perl lsb-release

#RUN tools/run-autotests.sh
#RUN tools/run-e2e-tests.sh unsafe
